/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gm;

/**
 *
 * @author nao07
 */
public class InventarioA extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventarioA.class.getName());

    /**
     * Creates new form InventarioA
     */
    public InventarioA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTituloI = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblGM = new javax.swing.JLabel();
        btnCerrarS = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblProductosActivos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblStockBajo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblEntradasHoy = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblSalidasHoy = new javax.swing.JLabel();
        panelInventario = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblInventarioActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 750));

        panelFondo.setBackground(new java.awt.Color(0, 51, 102));
        panelFondo.setMinimumSize(new java.awt.Dimension(1071, 600));
        panelFondo.setPreferredSize(new java.awt.Dimension(1100, 700));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gm/logo.png"))); // NOI18N
        lblLogo.setText("jLabel1");
        panelFondo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 158, -1));

        lblTituloI.setFont(new java.awt.Font("Segoe UI Semibold", 1, 32)); // NOI18N
        lblTituloI.setForeground(new java.awt.Color(214, 204, 25));
        lblTituloI.setText("INVENTARIO EN TIEMPO REAL");
        panelFondo.add(lblTituloI, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 34, -1, -1));

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitulo.setText("Monitorea y administra el inventario disponible");
        panelFondo.add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 83, 398, -1));

        lblGM.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lblGM.setForeground(new java.awt.Color(255, 255, 255));
        lblGM.setText("Grupo Modelo");
        panelFondo.add(lblGM, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 12, 122, 16));

        btnCerrarS.setBackground(new java.awt.Color(192, 14, 14));
        btnCerrarS.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnCerrarS.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarS.setText("Cerrar Sesión");
        btnCerrarS.addActionListener(this::btnCerrarSActionPerformed);
        panelFondo.add(btnCerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 60, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(226, 211, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        panelFondo.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 60, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductosActivos.setBackground(new java.awt.Color(0, 51, 102));
        lblProductosActivos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductosActivos.setForeground(new java.awt.Color(214, 204, 25));
        lblProductosActivos.setText("Productos activos");
        jPanel1.add(lblProductosActivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 138, 40));

        panelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 180, 200, 90));

        lblStockBajo.setBackground(new java.awt.Color(0, 51, 102));
        lblStockBajo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStockBajo.setForeground(new java.awt.Color(214, 204, 25));
        lblStockBajo.setText("Stock bajo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(lblStockBajo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblStockBajo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 180, -1, 90));

        lblEntradasHoy.setBackground(new java.awt.Color(0, 51, 102));
        lblEntradasHoy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEntradasHoy.setForeground(new java.awt.Color(214, 204, 25));
        lblEntradasHoy.setText("Entradas hoy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(lblEntradasHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblEntradasHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelFondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, 90));

        lblSalidasHoy.setBackground(new java.awt.Color(0, 51, 102));
        lblSalidasHoy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSalidasHoy.setForeground(new java.awt.Color(214, 204, 25));
        lblSalidasHoy.setText("Salidas hoy");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(lblSalidasHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblSalidasHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        panelFondo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 180, -1, -1));

        jPanel5.setBackground(new java.awt.Color(214, 204, 25));

        lblInventarioActual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblInventarioActual.setForeground(new java.awt.Color(0, 51, 102));
        lblInventarioActual.setText("Inventario actual");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Stock actual", "Entradas", "Salidas", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblInventarioActual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInventarioActual, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInventarioLayout = new javax.swing.GroupLayout(panelInventario);
        panelInventario.setLayout(panelInventarioLayout);
        panelInventarioLayout.setHorizontalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelInventarioLayout.setVerticalGroup(
            panelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventarioLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelFondo.add(panelInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 300, -1, 406));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InventarioA().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrarS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEntradasHoy;
    private javax.swing.JLabel lblGM;
    private javax.swing.JLabel lblInventarioActual;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblProductosActivos;
    private javax.swing.JLabel lblSalidasHoy;
    private javax.swing.JLabel lblStockBajo;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTituloI;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelInventario;
    // End of variables declaration//GEN-END:variables
}
