/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PanelA extends javax.swing.JPanel {

    public PanelA() {
        initComponents();
        // Llamamos al método aquí para que cargue los datos al iniciar el panel
        //cargarPedidos(); 
    }
/*
  public void cargarPedidos() {
    String url = "jdbc:mysql://localhost:3306/velora_db?useSSL=false&serverTimezone=UTC"; 
    String usuario = "root"; 
    String contrasena = "VeloraUtj07?"; 
    
    // Creamos un modelo de tabla fresco
    DefaultTableModel modelo = new DefaultTableModel(); 
    jTable1.setModel(modelo);
    
    // Títulos de las columnas (Incluyendo Productos)
    String[] titulos = {"ID Pedido", "Cliente", "Teléfono", "Dirección", "Referencias", "Productos", "Fecha", "Total ($)", "Estado"};
    modelo.setColumnIdentifiers(titulos);
    
    // 
    modelo.setRowCount(0); 
    
    String sql = "SELECT * FROM pedidos"; 
    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver"); 
        Connection con = DriverManager.getConnection(url, usuario, contrasena);
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
        
        while (rs.next()) {
            Object[] fila = {
                rs.getInt("id_pedido"),
                rs.getString("cliente_nombre"),
                rs.getString("telefono"),
                rs.getString("direccion"),
                rs.getString("referencias"),
                rs.getString("productos"), // Jalamos el producto recién insertado
                rs.getString("fecha"),
                rs.getBigDecimal("total"),
                rs.getString("estado")
            };
            modelo.addRow(fila);
        }
        
        rs.close();
        st.close();
        con.close();
        System.out.println("¡Tabla actualizada con éxito y sin duplicados!");
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error del sistema: " + ex.getMessage());
    }
}

    

    // De aquí para abajo continuará el código gris generado por NetBeans (initComponents, etc.)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrarS = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        tblPedidos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(246, 217, 55));

        btnCerrarS.setBackground(java.awt.Color.red);
        btnCerrarS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarS.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarS.setLabel("Cerrar Sesión");
        btnCerrarS.addActionListener(this::btnCerrarSActionPerformed);

        btnActualizar.setBackground(new java.awt.Color(0, 51, 102));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        tblPedidos.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Panel Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(659, 659, 659)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarS)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(635, 635, 635)
                .addComponent(tblPedidos))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCerrarS)
                            .addComponent(btnActualizar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)))
                .addGap(25, 25, 25)
                .addComponent(tblPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PEDIDO", "CLIENTE", "TELÉFONO", "DIRECCIÓN", "REFERENCIAS", "PRODUCTOS", "FECHA", "TOTAL ($)", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarTablaCarrito() {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();

    modelo.addColumn("Producto");
    modelo.addColumn("Cantidad");
    modelo.addColumn("Precio");
    modelo.addColumn("Subtotal");

    for (int i = 0; i < DatosCarrito.totalProductos; i++) {
        double subtotal = DatosCarrito.cantidades[i] * DatosCarrito.precios[i];

        Object[] fila = {
            DatosCarrito.productos[i],
            DatosCarrito.cantidades[i],
            "$" + DatosCarrito.precios[i],
            "$" + subtotal
        };

        modelo.addRow(fila);
    }

    jTable1.setModel(modelo);
}
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarTablaCarrito();
    javax.swing.JOptionPane.showMessageDialog(this, "Tabla actualizada correctamente.");
    
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSActionPerformed
        javax.swing.JFrame ventana = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

    if (ventana != null) {
        ventana.setContentPane(new LoginA());
        ventana.pack();
        ventana.setLocationRelativeTo(null);
        ventana.revalidate();
        ventana.repaint();
    }
    }//GEN-LAST:event_btnCerrarSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCerrarS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JScrollPane tblPedidos;
    // End of variables declaration//GEN-END:variables
}
