/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gm;   
/**
 *
 * @author nao07
 */
public class Registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblContraRegristro = new javax.swing.JLabel();
        lblNombreCom = new javax.swing.JLabel();
        txtNombreComRegistro = new javax.swing.JTextField();
        lblRegistrate = new javax.swing.JLabel();
        lblCorreoRegistro = new javax.swing.JLabel();
        txtCorreoElecRegistro = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();
        btnCrearCuenta = new javax.swing.JToggleButton();
        lblLogo = new javax.swing.JLabel();
        lblSlogan1 = new javax.swing.JLabel();
        lblSlogan2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 0));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        lblContraRegristro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContraRegristro.setForeground(new java.awt.Color(255, 255, 255));
        lblContraRegristro.setText("Contraseña");

        lblNombreCom.setBackground(new java.awt.Color(0, 0, 0));
        lblNombreCom.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombreCom.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCom.setText("Nombre Completo");

        txtNombreComRegistro.addActionListener(this::txtNombreComRegistroActionPerformed);

        lblRegistrate.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblRegistrate.setForeground(new java.awt.Color(215, 206, 25));
        lblRegistrate.setText("REGÍSTRATE");
        lblRegistrate.setMaximumSize(new java.awt.Dimension(32767, 32767));
        lblRegistrate.setPreferredSize(new java.awt.Dimension(232, 48));

        lblCorreoRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCorreoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreoRegistro.setText("Correo Electrónico");

        txtContrasena.addActionListener(this::txtContrasenaActionPerformed);

        btnCrearCuenta.setBackground(new java.awt.Color(215, 206, 25));
        btnCrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCuenta.setText("CREAR CUENTA");
        btnCrearCuenta.addActionListener(this::btnCrearCuentaActionPerformed);

        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\nao07\\OneDrive\\Documentos\\NetBeansProjects\\GM\\src\\gm\\pictures\\logo.png")); // NOI18N
        lblLogo.setText("jLabel5");

        lblSlogan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSlogan1.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan1.setText("100 años impulsando el Extra de México");

        lblSlogan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSlogan2.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan2.setText("Gracias por dejarnos ser parte.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(btnCrearCuenta)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRegistrate, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCorreoElecRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCorreoRegistro)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addComponent(lblContraRegristro))
                                        .addComponent(txtNombreComRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNombreCom)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSlogan1)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSlogan2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblLogo)
                        .addGap(31, 31, 31)
                        .addComponent(lblSlogan1)
                        .addGap(18, 18, 18)
                        .addComponent(lblSlogan2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblRegistrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblNombreCom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreComRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lblCorreoRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreoElecRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblContraRegristro)
                        .addGap(12, 12, 12)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(btnCrearCuenta)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreComRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreComRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreComRegistroActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        String nombre = txtNombreComRegistro.getText().trim();
String correo = txtCorreoElecRegistro.getText().trim();
String contrasena = txtContrasena.getText().trim();
String rol = "usuario";

if (nombre.isEmpty() || correo.isEmpty() || contrasena.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor llena todos los campos.");
    return;
}

if (!correo.contains("@") || !correo.contains(".")) {
    javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un correo válido.");
    return;
}

boolean guardado = Conexion.registrarUsuario(nombre, correo, contrasena, rol);

if (!guardado) {
    javax.swing.JOptionPane.showMessageDialog(this, "Ese correo ya está registrado.");
    return;
}

javax.swing.JOptionPane.showMessageDialog(this, "Cuenta creada correctamente. Ahora inicia sesión.");

// Regresar a pantalla de Login
javax.swing.JFrame ventanaLogin = new javax.swing.JFrame("Inicia Sesión");
ventanaLogin.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
ventanaLogin.setContentPane(new LoginA());
ventanaLogin.pack();
ventanaLogin.setLocationRelativeTo(null);
ventanaLogin.setVisible(true);

// Cerrar registro
this.dispose();
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCrearCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraRegristro;
    private javax.swing.JLabel lblCorreoRegistro;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreCom;
    private javax.swing.JLabel lblRegistrate;
    private javax.swing.JLabel lblSlogan1;
    private javax.swing.JLabel lblSlogan2;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCorreoElecRegistro;
    private javax.swing.JTextField txtNombreComRegistro;
    // End of variables declaration//GEN-END:variables
}
