/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gm;

/**
 *
 * @author alber
 */
public class LoginA extends javax.swing.JPanel {

    /**
     * Creates new form LoginA
     */
    public LoginA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIniciaS = new javax.swing.JLabel();
        lblCorreoE = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCorreo = new javax.swing.JTextPane();
        lblContra = new javax.swing.JLabel();
        txtContrasenaInicioS = new javax.swing.JPasswordField();
        btnIniciarS = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSloganIniciaS1 = new javax.swing.JLabel();
        lblSloganIniciaS2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegistrarse = new javax.swing.JButton();
        lblRegistro = new javax.swing.JLabel();
        lblLogoIniciaSesion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 102));

        lblIniciaS.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblIniciaS.setForeground(new java.awt.Color(215, 206, 25));
        lblIniciaS.setText("INICIA SESIÓN");

        lblCorreoE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCorreoE.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreoE.setText("Correo Electronico");

        jScrollPane1.setViewportView(txtCorreo);

        lblContra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContra.setForeground(new java.awt.Color(255, 255, 255));
        lblContra.setText("Contraseña");

        txtContrasenaInicioS.setPreferredSize(new java.awt.Dimension(62, 20));
        txtContrasenaInicioS.addActionListener(this::txtContrasenaInicioSActionPerformed);

        btnIniciarS.setBackground(new java.awt.Color(215, 206, 25));
        btnIniciarS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIniciarS.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarS.setText("INICIAR SESIÓN");
        btnIniciarS.addActionListener(this::btnIniciarSActionPerformed);

        lblSloganIniciaS1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSloganIniciaS1.setForeground(new java.awt.Color(255, 255, 255));
        lblSloganIniciaS1.setText("100 años impulsando el Extra de México");

        lblSloganIniciaS2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSloganIniciaS2.setForeground(new java.awt.Color(255, 255, 255));
        lblSloganIniciaS2.setText("Gracias por dejarnos ser parte.");

        btnRegistrarse.setText("Regístrate aquí");
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.setDefaultCapable(false);
        btnRegistrarse.setFocusPainted(false);
        btnRegistrarse.addActionListener(this::btnRegistrarseActionPerformed);

        lblRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistro.setText("¿No tienes cuenta?");

        lblLogoIniciaSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\nao07\\OneDrive\\Documentos\\NetBeansProjects\\GM\\src\\gm\\pictures\\logo.png")); // NOI18N
        lblLogoIniciaSesion.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblSloganIniciaS1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(lblSloganIniciaS2)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblLogoIniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)))))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIniciarS, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContrasenaInicioS, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCorreoE)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblContra)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblIniciaS)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblRegistro)
                                .addGap(96, 96, 96))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogoIniciaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblSloganIniciaS1)
                .addGap(18, 18, 18)
                .addComponent(lblSloganIniciaS2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblIniciaS)
                .addGap(42, 42, 42)
                .addComponent(lblCorreoE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblContra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenaInicioS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciarS)
                .addGap(30, 30, 30)
                .addComponent(lblRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarse)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtContrasenaInicioSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaInicioSActionPerformed
        btnIniciarS.doClick();
        
    }//GEN-LAST:event_txtContrasenaInicioSActionPerformed

    private void btnIniciarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSActionPerformed
        String correo = txtCorreo.getText().trim();
String contrasena = new String(txtContrasenaInicioS.getPassword()).trim();

if (correo.isEmpty() || contrasena.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Correo y contraseña necesarios. Intente nuevamente.");
    return;
}

if (correo.equalsIgnoreCase("admin") && contrasena.equals("admin")) {

    javax.swing.JFrame ventana = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

    if (ventana != null) {
        ventana.setContentPane(new PanelA());
        ventana.pack();
        ventana.setLocationRelativeTo(null);
        ventana.revalidate();
        ventana.repaint();
    }

} else {

    String rol = Conexion.validarUsuario(correo, contrasena);

    if (rol != null && rol.equals("usuario")) {

        CatalogoC_1 catalogo = new CatalogoC_1();
        catalogo.setLocationRelativeTo(null);
        catalogo.setVisible(true);

        java.awt.Window login = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (login != null) {
            login.dispose();
        }

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.");
    }
}
    }//GEN-LAST:event_btnIniciarSActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
       Registro ventana = new Registro();
    ventana.setLocationRelativeTo(null);
    ventana.setVisible(true);

    java.awt.Window login = javax.swing.SwingUtilities.getWindowAncestor(this);

    if (login != null) {
        login.dispose();
    }
    }//GEN-LAST:event_btnRegistrarseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarS;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContra;
    private javax.swing.JLabel lblCorreoE;
    private javax.swing.JLabel lblIniciaS;
    private javax.swing.JLabel lblLogoIniciaSesion;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblSloganIniciaS1;
    private javax.swing.JLabel lblSloganIniciaS2;
    private javax.swing.JPasswordField txtContrasenaInicioS;
    private javax.swing.JTextPane txtCorreo;
    // End of variables declaration//GEN-END:variables
}
